version: '3.8'
services:
  redis:
    image: redis
    container_name: cache
    # expose:
    #   - 6379
    ports:
      - "6379:6379"
  app:
    build: ./
    volumes:
      - ./:/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - 3000:3000
    environment:
      # - REDIS_URL=redis://cache
      NODE_ENV: development
      PORT: 3000
      # - REDIS_HOST=redis://localhost
      # - REDIS_HOST=redis://redis
      # - REDIS_HOST=redis://localhost
      REDIS_HOST: cache
      REDIS_PORT: 6379
    # command:
    #   sh -c 'npm i && node server.js'


# version: "3.8"
# services:
#     redis_db:
#         image: "redis:alpine"
#         ports:
#             - "8080:6379"
#     web:
#         container_name: node-app
#         build: ./
#         # volumes:
#         #   - ./:/var/www/app
#         links:
#           - redis_db
#         ports:
#             - "3000:3000"
#         environment:
#         - NODE_ENV=development
#         - PORT=3000
#         - REDIS_HOST=redis://redis_db:6379
#         - REDIS_PORT=6379
